Update/modules
MasaCMS/documentation pull request #24
Opened 2022-11-03 10:32 UTC by grantshepert

2022-11-03 12:13 UTC, guustnieuwenhuis requested changes
Add a label to the top of the page for the new features in 7.4. As done on this page for 7.3: https://docs.masacms.com/front-end-layout-manager/m-tag/masa-scope/

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/01_introduction/01_layout-manager.md
> +Instead of relying upon hard-coded, code-based layout templates, the Layout Manager allows you to drag-and-drop highly configurable "Modules"  onto a page. Each Module (depending upon it's type and l
double space

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/01_introduction/01_layout-manager.md
> +To enable the Layout Manager, log into Masa with an account that has editing permissions enabled, then from the top editor toolbar choose "Edit (pencil icon) -> Inline Edit". A list of Modules will a
Masa CMS

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/02_modules/01_content.md
> +Component allows you to select or create a new Masa Component. Components are shared, reusable content blocks, so remember that editing an existing component will change the content wherever it is di
Masa CMS

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/02_modules/02_collections.md
> +A Local Index is a Collection of content you have created within the Masa Administrator.
Masa CMS

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/02_modules/07_plugins.md
> +A Masa Plugin may have it's own set of Modules (sometimes refered to as "display objects") to render it's front-end content. If a plugin has Modules/Display Objects associated with it, then these wil
Masa CMS

2022-11-03 12:13 UTC, guustnieuwenhuis commented on 04_front-end-layout-manager/02_modules/16_system.md
> +System places one of the Masa "system" Modules onto the page.
Masa CMS

2022-11-09 16:31 UTC, grantshepert commented
Updated, new content, changes implemented.

2023-07-15 08:11 UTC, guustnieuwenhuis approved these changes

2023-07-15 08:13 UTC, merged